version: '2'
services:
    mongoex-mongodb:
        container_name: mongoex-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/MongoEx/mongodb/:/data/db/
